// <auto-generated />
using System;
using DiveDeepWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeepWebApp.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    [Migration("20260911081519_BookingProducts")]
    partial class BookingProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeepWebApp.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.BookingProduct", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BookingProducts", (string)null);
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Dykkerdragter"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Image = new byte[0],
                            Name = "Tanke"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Image = new byte[0],
                            Name = "Regulatorsæt"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Maske/Snorkel"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Finner"
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.BCD", b =>
                {
                    b.HasBaseType("DiveDeepWebApp.Models.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BCDs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "Navigator Lite BCD",
                            Price = 125.0,
                            Model = "Navigator Lite BCD",
                            Size = "S"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "Navigator Lite BCD",
                            Price = 125.0,
                            Model = "Navigator Lite BCD",
                            Size = "M"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "Navigator Lite BCD",
                            Price = 125.0,
                            Model = "Navigator Lite BCD",
                            Size = "L"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Glide",
                            Price = 140.0,
                            Model = "BCD Glide",
                            Size = "S"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Glide",
                            Price = 140.0,
                            Model = "BCD Glide",
                            Size = "M"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Glide",
                            Price = 140.0,
                            Model = "BCD Glide",
                            Size = "L"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Hydros Pro",
                            Price = 200.0,
                            Model = "BCD Hydros Pro",
                            Size = "S"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Hydros Pro",
                            Price = 200.0,
                            Model = "BCD Hydros Pro",
                            Size = "M"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Scubapro",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Hydros Pro",
                            Price = 200.0,
                            Model = "BCD Hydros Pro",
                            Size = "L"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Seac",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Modular",
                            Price = 145.0,
                            Model = "BCD Modular",
                            Size = "S"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Seac",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Modular",
                            Price = 145.0,
                            Model = "BCD Modular",
                            Size = "M"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Seac",
                            CategoryId = 1,
                            Description = "",
                            Image = new byte[0],
                            Name = "BCD Modular",
                            Price = 145.0,
                            Model = "BCD Modular",
                            Size = "L"
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Fin", b =>
                {
                    b.HasBaseType("DiveDeepWebApp.Models.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Fins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 107,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Jet Fin",
                            Price = 50.0,
                            Model = "Jet Fin",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 108,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Jet Fin",
                            Price = 50.0,
                            Model = "Jet Fin",
                            Size = "S"
                        },
                        new
                        {
                            Id = 109,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Jet Fin",
                            Price = 50.0,
                            Model = "Jet Fin",
                            Size = "M"
                        },
                        new
                        {
                            Id = 110,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Jet Fin",
                            Price = 50.0,
                            Model = "Jet Fin",
                            Size = "L"
                        },
                        new
                        {
                            Id = 111,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Jet Fin",
                            Price = 50.0,
                            Model = "Jet Fin",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 112,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "GO Travel",
                            Price = 50.0,
                            Model = "GO Travel",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 113,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "GO Travel",
                            Price = 50.0,
                            Model = "GO Travel",
                            Size = "S"
                        },
                        new
                        {
                            Id = 114,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "GO Travel",
                            Price = 50.0,
                            Model = "GO Travel",
                            Size = "M"
                        },
                        new
                        {
                            Id = 115,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "GO Travel",
                            Price = 50.0,
                            Model = "GO Travel",
                            Size = "L"
                        },
                        new
                        {
                            Id = 116,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "GO Travel",
                            Price = 50.0,
                            Model = "GO Travel",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 117,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Seawing Supernova",
                            Price = 60.0,
                            Model = "Seawing Supernova",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 118,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Seawing Supernova",
                            Price = 60.0,
                            Model = "Seawing Supernova",
                            Size = "S"
                        },
                        new
                        {
                            Id = 119,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Seawing Supernova",
                            Price = 60.0,
                            Model = "Seawing Supernova",
                            Size = "M"
                        },
                        new
                        {
                            Id = 120,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Seawing Supernova",
                            Price = 60.0,
                            Model = "Seawing Supernova",
                            Size = "L"
                        },
                        new
                        {
                            Id = 121,
                            Brand = "Scubapro",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Seawing Supernova",
                            Price = 60.0,
                            Model = "Seawing Supernova",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 122,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Propulsion",
                            Price = 50.0,
                            Model = "Propulsion",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 123,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Propulsion",
                            Price = 50.0,
                            Model = "Propulsion",
                            Size = "S"
                        },
                        new
                        {
                            Id = 124,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Propulsion",
                            Price = 50.0,
                            Model = "Propulsion",
                            Size = "M"
                        },
                        new
                        {
                            Id = 125,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Propulsion",
                            Price = 50.0,
                            Model = "Propulsion",
                            Size = "L"
                        },
                        new
                        {
                            Id = 126,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Propulsion",
                            Price = 50.0,
                            Model = "Propulsion",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 127,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "ALA",
                            Price = 50.0,
                            Model = "ALA",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 128,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "ALA",
                            Price = 50.0,
                            Model = "ALA",
                            Size = "S"
                        },
                        new
                        {
                            Id = 129,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "ALA",
                            Price = 50.0,
                            Model = "ALA",
                            Size = "M"
                        },
                        new
                        {
                            Id = 130,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "ALA",
                            Price = 50.0,
                            Model = "ALA",
                            Size = "L"
                        },
                        new
                        {
                            Id = 131,
                            Brand = "Seac",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "ALA",
                            Price = 50.0,
                            Model = "ALA",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 132,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Tech",
                            Price = 75.0,
                            Model = "Tech",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 133,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Tech",
                            Price = 75.0,
                            Model = "Tech",
                            Size = "S"
                        },
                        new
                        {
                            Id = 134,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Tech",
                            Price = 75.0,
                            Model = "Tech",
                            Size = "M"
                        },
                        new
                        {
                            Id = 135,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Tech",
                            Price = 75.0,
                            Model = "Tech",
                            Size = "L"
                        },
                        new
                        {
                            Id = 136,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Tech",
                            Price = 75.0,
                            Model = "Tech",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 137,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Rec Fin",
                            Price = 80.0,
                            Model = "Rec Fin",
                            Size = "XS"
                        },
                        new
                        {
                            Id = 138,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Rec Fin",
                            Price = 80.0,
                            Model = "Rec Fin",
                            Size = "S"
                        },
                        new
                        {
                            Id = 139,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Rec Fin",
                            Price = 80.0,
                            Model = "Rec Fin",
                            Size = "M"
                        },
                        new
                        {
                            Id = 140,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Rec Fin",
                            Price = 80.0,
                            Model = "Rec Fin",
                            Size = "L"
                        },
                        new
                        {
                            Id = 141,
                            Brand = "Fourth Element",
                            CategoryId = 6,
                            Description = "",
                            Image = new byte[0],
                            Name = "Rec Fin",
                            Price = 80.0,
                            Model = "Rec Fin",
                            Size = "XL"
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Mask", b =>
                {
                    b.HasBaseType("DiveDeepWebApp.Models.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Masks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Brand = "Scubapro",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Ghost",
                            Price = 50.0,
                            Model = "Ghost"
                        },
                        new
                        {
                            Id = 101,
                            Brand = "Scubapro",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "D-Mask",
                            Price = 60.0,
                            Model = "D-Mask"
                        },
                        new
                        {
                            Id = 102,
                            Brand = "Scubapro",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Spectra Mini",
                            Price = 50.0,
                            Model = "Spectra Mini"
                        },
                        new
                        {
                            Id = 103,
                            Brand = "Scubapro",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Crystal VU",
                            Price = 75.0,
                            Model = "Crystal VU"
                        },
                        new
                        {
                            Id = 104,
                            Brand = "Fourth Element",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Scout Kontrast",
                            Price = 75.0,
                            Model = "Scout Kontrast"
                        },
                        new
                        {
                            Id = 105,
                            Brand = "Fourth Element",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Scout Enhance",
                            Price = 75.0,
                            Model = "Scout Enhance"
                        },
                        new
                        {
                            Id = 106,
                            Brand = "Tusa",
                            CategoryId = 5,
                            Description = "",
                            Image = new byte[0],
                            Name = "Element",
                            Price = 75.0,
                            Model = "Element"
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Regulator", b =>
                {
                    b.HasBaseType("DiveDeepWebApp.Models.Product");

                    b.Property<string>("FirstStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Regulators", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 97,
                            Brand = "Scubapro",
                            CategoryId = 4,
                            Description = "",
                            Image = new byte[0],
                            Name = "MK25EVO / S600",
                            Price = 125.0,
                            FirstStage = "MK25EVO",
                            Octopus = "R105",
                            SecondStage = "S600"
                        },
                        new
                        {
                            Id = 98,
                            Brand = "Scubapro",
                            CategoryId = 4,
                            Description = "",
                            Image = new byte[0],
                            Name = "MK17EVO / C370",
                            Price = 100.0,
                            FirstStage = "MK17EVO",
                            Octopus = "R095",
                            SecondStage = "C370"
                        },
                        new
                        {
                            Id = 99,
                            Brand = "Scubapro",
                            CategoryId = 4,
                            Description = "",
                            Image = new byte[0],
                            Name = "MK25EVO BT / A700 Carbon BT",
                            Price = 150.0,
                            FirstStage = "MK25EVO BT",
                            Octopus = "S270",
                            SecondStage = "A700 Carbon BT"
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Suit", b =>
                {
                    b.HasBaseType("DiveDeepWebApp.Models.Product");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Suits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "XS",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "S",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "M",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "L",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "XL",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "XS",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "S",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "M",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "L",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "XL",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "XS",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "S",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "M",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "L",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "Definition",
                            Size = "XL",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "XS",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "S",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "M",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "L",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "XL",
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "XS",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "S",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "M",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "L",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "XL",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "XS",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "S",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "M",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "L",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Definition",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "Definition",
                            Size = "XL",
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "W5",
                            Size = "XS",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "W5",
                            Size = "S",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "W5",
                            Size = "M",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "W5",
                            Size = "L",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Herre",
                            Model = "W5",
                            Size = "XL",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "W5",
                            Size = "XS",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "W5",
                            Size = "S",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "W5",
                            Size = "M",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "W5",
                            Size = "L",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "W5",
                            Price = 100.0,
                            Gender = "Dame",
                            Model = "W5",
                            Size = "XL",
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Herre",
                            Model = "Proteus",
                            Size = "XS",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 54,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Herre",
                            Model = "Proteus",
                            Size = "S",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Herre",
                            Model = "Proteus",
                            Size = "M",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Herre",
                            Model = "Proteus",
                            Size = "L",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 57,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Herre",
                            Model = "Proteus",
                            Size = "XL",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Dame",
                            Model = "Proteus",
                            Size = "XS",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 59,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Dame",
                            Model = "Proteus",
                            Size = "S",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Dame",
                            Model = "Proteus",
                            Size = "M",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Dame",
                            Model = "Proteus",
                            Size = "L",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 62,
                            Brand = "Fourth Element",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Proteus",
                            Price = 120.0,
                            Gender = "Dame",
                            Model = "Proteus",
                            Size = "XL",
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 63,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Size = "XS",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Size = "S",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 65,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Size = "M",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 66,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Size = "L",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 67,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Size = "XL",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 68,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Size = "XS",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 69,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Size = "S",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 70,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Size = "M",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 71,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Size = "L",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 72,
                            Brand = "Scubapro",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "Exodry 4.0",
                            Price = 300.0,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Size = "XL",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 73,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Size = "XS",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Size = "S",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 75,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Size = "M",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 76,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Size = "L",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 77,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Size = "XL",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 78,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Size = "XS",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 79,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Size = "S",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 80,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Size = "M",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 81,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Size = "L",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 82,
                            Brand = "Waterproof",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "D7 Evo",
                            Price = 320.0,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Size = "XL",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 83,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Size = "XS",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 84,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Size = "S",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 85,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Size = "M",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 86,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Size = "L",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 87,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Size = "XL",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 88,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Size = "XS",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 89,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Size = "S",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 90,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Size = "M",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 91,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Size = "L",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 92,
                            Brand = "Santi",
                            CategoryId = 2,
                            Description = "",
                            Image = new byte[0],
                            Name = "E.Lite Plus",
                            Price = 350.0,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Size = "XL",
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Tank", b =>
                {
                    b.HasBaseType("DiveDeepWebApp.Models.Product");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.ToTable("Tanks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 93,
                            Brand = "Scubapro",
                            CategoryId = 3,
                            Description = "",
                            Image = new byte[0],
                            Name = "5L tank",
                            Price = 150.0,
                            Volume = 5
                        },
                        new
                        {
                            Id = 94,
                            Brand = "Scubapro",
                            CategoryId = 3,
                            Description = "",
                            Image = new byte[0],
                            Name = "10L tank",
                            Price = 160.0,
                            Volume = 10
                        },
                        new
                        {
                            Id = 95,
                            Brand = "Scubapro",
                            CategoryId = 3,
                            Description = "",
                            Image = new byte[0],
                            Name = "12L tank",
                            Price = 170.0,
                            Volume = 12
                        },
                        new
                        {
                            Id = 96,
                            Brand = "Scubapro",
                            CategoryId = 3,
                            Description = "",
                            Image = new byte[0],
                            Name = "15L tank",
                            Price = 180.0,
                            Volume = 15
                        });
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.BookingProduct", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Booking", "Booking")
                        .WithMany("BookingProducts")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeepWebApp.Models.Product", "Product")
                        .WithMany("BookingProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Product", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.BCD", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeepWebApp.Models.BCD", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Fin", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeepWebApp.Models.Fin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Mask", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeepWebApp.Models.Mask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Regulator", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeepWebApp.Models.Regulator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Suit", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeepWebApp.Models.Suit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Tank", b =>
                {
                    b.HasOne("DiveDeepWebApp.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("DiveDeepWebApp.Models.Tank", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Booking", b =>
                {
                    b.Navigation("BookingProducts");
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepWebApp.Models.Product", b =>
                {
                    b.Navigation("BookingProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
